### ISSUE TITLE
Space/swap issues?

### ISSUE THREAD

**Issue by schmug** [cimryan/teslausb#129]
I've just started monitoring my pi in Zabbix and was wondering if these indicate problems with my installation that should be addressed:

`Filesystem     1K-blocks     Used Available Use% Mounted on`
`/dev/mmcblk0p3  59229116 56190760         0 100% /backingfiles`

`              total        used        free      shared  buff/cache   available`
`Mem:         443844       27776      236024        6228      180044      360544`
`Swap:             0           0           0`

**Comment by marcone** [comment]
By default teslausb will use all available space in the backingfiles partition for recordings and music, so it's expected to be full (there will be one or two large files in there, cam_disk.bin and optionally music_disk.bin that together take up all available space).
If you want to keep some space available, you can use my branch (therealmarcone/main-dev) and specify the exact size you want for camera and recordings, leaving unused space if desired.

I don't think swap is enabled by default (and I'm not sure you'd want to swap to an sd card), so that seems OK too.
