### ISSUE TITLE
The setup script assumes the file share is pingable

### ISSUE THREAD

**Issue by Cisien** [cimryan/teslausb#87]
I am attempting to set this up to upload files to an azure storage file share. I can manually mount the share on the pi, however, it fails when using the same values in the setup script.

What is the reason for using the IP address instead of the name supplied?

I'm planning on modifying this in my repo to skip this and use the name instead of IP. I can PR that change if desired.

**Comment by cimryan** [comment]
The principal reason is because that's how it the script was written by the original author and we haven't found a need to change it.

Looking around on the internet, I could speculate that perhaps the reason it was written that way was in case the mount happened before name resolution happened. But I've read that there's a "_netfs_ option that could also address this.

It sounds like you're saying that your archive server
1. Doesn't have a stable IP address
2. Isn't pingable

Is that right?

**Comment by Cisien** [comment]
I'm not sure how stable the IP address is, since this is fully Azure hosted, but they definitely block icmp ping on that address.

**Comment by Cisien** [comment]
it looks like the 'hping3' package can be used `hping3 -c 1 -S -p 445 $hostname` instead in order to test for connectivity to a cifs share.

**Comment by cimryan** [comment]
Does hping3 work for all CIFS shares, on Windows, MacOS, Samba, others? If so, it seems reasonable to replace the ping test with that test for CIFS archives.

The alternative would be to add Azure File Share as another hosting technology. The current organization of the files actually makes that option easier, but it would be nice to consolidate all the CIFS options.

**Comment by Cisien** [comment]
I have only tested with azure's file shares, but I believe it should work. It works by using a TCP SYN to test if the port is open and listening.

**Comment by cimryan** [comment]
If you'll submit a PR I'll be happy to merge it into a branch in this repo to increase the chance that someone will try out the change with a Windows share.

**Comment by Cisien** [comment]
https://github.com/cimryan/teslausb/pull/92

I've done some very basic testing locally with my windows 10 pc, and a freenas samba server I have running, and hping3 worked well.

**Comment by cimryan** [comment]
Merged!
